import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import path from 'path'

export default defineConfig({
  plugins: [vue()],
  root: '.',
  publicDir: '../public', // Serve static assets from parent public folder (including api)
  base: './',
  build: {
    outDir: '../public',
    emptyOutDir: false, // Keep api files generated by python script
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html')
      }
    }
  }
})
